creds:
  dump_results: true
  files_dump_folder: "./dumps"
  redis:
    host: redis
    port: 6379
    db: 0

services:
  combinations:
    analytes: ["Acetone", "Benzene", "Methanol", "Ethanol", "IPA"]
    sensors:
      [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 17, 18, 19, 20]
