version: 1
disable_existing_loggers: false

formatters:
  default:
    format: "[%(asctime)s] [%(levelname)s] [%(funcName)s] %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"

handlers:
  console:
    class: "logging.StreamHandler"
    level: "DEBUG"
    formatter: "default"
    stream: "ext://sys.stdout"

loggers:
  custom:
    level: DEBUG
    handlers: ["console"]
